package com.wbg.swager.entity;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.petId
     *
     * @mbg.generated
     */
    private Integer petid;

    public Pet getPet() {
        return pet;
    }

    public void setPet(Pet pet) {
        this.pet = pet;
    }

    private Pet pet;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipDate
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date shipdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.complete
     *
     * @mbg.generated
     */
    private Boolean complete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.petId
     *
     * @return the value of orders.petId
     * @mbg.generated
     */
    public Integer getPetid() {
        return petid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.petId
     *
     * @param petid the value for orders.petId
     * @mbg.generated
     */
    public void setPetid(Integer petid) {
        this.petid = petid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.quantity
     *
     * @return the value of orders.quantity
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.quantity
     *
     * @param quantity the value for orders.quantity
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipDate
     *
     * @return the value of orders.shipDate
     * @mbg.generated
     */

    public Date getShipdate() {
        return shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipDate
     *
     * @param shipdate the value for orders.shipDate
     * @mbg.generated
     */
    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.complete
     *
     * @return the value of orders.complete
     * @mbg.generated
     */
    public Boolean getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.complete
     *
     * @param complete the value for orders.complete
     * @mbg.generated
     */
    public void setComplete(Boolean complete) {
        this.complete = complete;
    }
}