package com.wbg.swager.entity;

public class Pet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.id
     *
     * @mbg.generated
     */
    private Integer id;

    private Category category;
    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Tag getTag() {
        return tag;
    }

    public void setTag(Tag tag) {
        this.tag = tag;
    }

    private Tag tag;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.photoUrls
     *
     * @mbg.generated
     */
    private String photourls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.tags
     *
     * @mbg.generated
     */
    private Integer tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.id
     *
     * @return the value of pet.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.id
     *
     * @param id the value for pet.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.category_id
     *
     * @return the value of pet.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.category_id
     *
     * @param categoryId the value for pet.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.name
     *
     * @return the value of pet.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.name
     *
     * @param name the value for pet.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.photoUrls
     *
     * @return the value of pet.photoUrls
     *
     * @mbg.generated
     */
    public String getPhotourls() {
        return photourls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.photoUrls
     *
     * @param photourls the value for pet.photoUrls
     *
     * @mbg.generated
     */
    public void setPhotourls(String photourls) {
        this.photourls = photourls == null ? null : photourls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.tags
     *
     * @return the value of pet.tags
     *
     * @mbg.generated
     */
    public Integer getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.tags
     *
     * @param tags the value for pet.tags
     *
     * @mbg.generated
     */
    public void setTags(Integer tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.status
     *
     * @return the value of pet.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.status
     *
     * @param status the value for pet.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}